import { Linking } from 'react-native'
import { themeColors } from '../theme'

export const categories = [
  {
    id: 1,
    title: "All",
  },
  {
    id: 2,
    title: "Engineering",
  },
  {
    id: 3,
    title: "Technology",
  },
  {
    id: 4,
    title: "Programming",
  },
  {
    id: 5,
    title: "Development",
  },
  {
    id: 6,
    title: "Gaming",
  },
]



export const clubItems = [
  {
    id: 1,
    name: 'IEEE',
    tag1: 'engineering',
    tag2: 'technology',
    tag3: 'community',
    tag4: 'all',
    stacks1: 'Research',
    stacks2: 'technology',
    stacks3: 'Community',
    accent: '#76bde9',
    bgimage: require('../assets/images/22.png'),
    image: require('../assets/logos/ieee.png'),
    desc: 'IEEE (Institute of Electrical and Electronics Engineers) is a global community of engineers, scientists, and technologynology enthusiasts. Join us to network and collaborate on cutting-edge projects.'},
  
  {
    id: 2,
    name: 'Mobile Technologies',
    tag1: 'mobile',
    tag2: 'technology',
    tag3: 'apps',
    tag4: 'all',
    stacks1: 'Mobile Apps',
    stacks2: 'Android',
    stacks3: 'IOS',
    accent: '#cb6ce6',
    bgimage: require('../assets/images/14.png'),
    image: require('../assets/logos/MobileTech.png'),
    desc: 'Mobile technologies Club is all about staying updated on the latest mobile app development trends, platforms, and tools.',
    pic: 'no',
    img1: require('../assets/events/soon.png'),
    img2: require('../assets/events/soon.png'),
    img3: require('../assets/events/soon.png')},
  {
    id: 3,
    name: 'CodeChef',
    tag1: 'programming',
    tag2: 'development',
    tag3: 'challenges',
    tag4: 'all',
    stacks1: 'Competetions',
    stacks2: 'Challenges',
    stacks3: 'Coding',
    accent: '#6f3ac6',
    bgimage: require('../assets/images/3.png'),
    image: require('../assets/logos/codechef.png'),
    desc: 'CodeChef is your platform for competitive programming and coding challenges. Join us to improve your coding skills, solve algorithmic problems, and compete in coding contests.'  },
  
  {
    id: 4,
    name: 'Alan Turing Club',
    tag1: 'engineering',
    tag2: 'algorithems',
    tag3: 'mathematics',
    tag4: 'all',
    stacks1: 'Maths',
    stacks2: 'Algorithms',
    stacks3: 'Logic Building',
    accent: '#616161',
    bgimage: require('../assets/images/4.png'),
    image: require('../assets/logos/atc.png'),
    desc: 'Alan Turing Club aims to cultivate a community of exceptional coders, providing them with comprehensive resources and training to prepare for top companies. Our exclusive interactions with renowned tech experts ensure a holistic and transformative learning journey' ,
    vis: 'At Alan Turing Club, we aim to cultivate elite coders. We nurture potential, enhance skills, and prep for MAANG and Fortune 500 gigs. Our commitment includes resources, tests, and guru interactions for a transformative learning journey',
    pic: 'yes',
    cname: 'Udit Chaudhary',
    vname: 'Akshay Sinha',
    chair: require('../assets/team/atc.jpg'),
    vc: require('../assets/team/atcv.jpg'),
    img1: require('../assets/events/atc1.jpeg'),
    img2: require('../assets/events/atc2.jpeg'),
    img3: require('../assets/events/atc3.png')},
  {
    id: 5,
    name: 'Google Developer Student Club',
    tag1: 'development',
    tag2: 'community',
    tag3: 'technology',
    tag4: 'all',
    stacks1: 'Google',
    stacks2: 'Hackathons',
    stacks3: 'Workshops',
    accent: '#f4db7b',
    bgimage: require('../assets/images/21.png'),
    image: require('../assets/logos/GDSC.png'),
    desc: 'Google Developer Student Club is the official student community for Google Developers. Explore Google technologies, attend workshops, and participate in hackathons.'  },
  {
    id: 6,
    name: 'Association for Computing Machinery (ACM)',
    tag1: 'development',
    tag2: 'technology',
    tag3: 'profession',
    tag4: 'all',
    stacks1: 'Theories',
    stacks2: 'Profession',
    stacks3: 'technology',
    accent: '#76bde9',
    bgimage: require('../assets/images/22.png'),
    image: require('../assets/logos/ACM.png'),
    desc: 'ACM (Association for Computing Machinery) is dedicated to advancing computing as a science and profession. Join us to engage with computer science enthusiasts and explore the latest developments in the field.' },
  {
    id: 7,
    name: 'Product Development Team (PDT)',
    tag1: 'innovation',
    tag2: 'creativity',
    tag3: 'engineering',
    tag4: 'all',
    stacks1: 'Management',
    stacks2: 'Creativity',
    stacks3: 'Innovate',
    accent: '#5271ff',
    bgimage: require('../assets/images/19.png'),
    image: require('../assets/logos/PDT.png'),
    desc: 'PDT (Product Development Team) is all about turning ideas into reality. Join us if you are passionate about innovation and want to be part of creating exciting new products.' },
  {
    id: 8,
    name: 'Computer Society of India (CSI)',
    tag1: 'computerscience',
    tag2: 'technology',
    tag3: 'india',
    tag4: 'all',
    stacks1: 'Research',
    stacks2: 'Community',
    stacks3: 'Indian Society',
    accent: '#183883',
    bgimage: require('../assets/images/19.png'),
    image: require('../assets/logos/CSI.png'),
    desc: 'CSI (Computer Society of India) is committed to promoting the advancement of computer science in India. Connect with like-minded individuals and contribute to the technology community.' }, 
  {
    id: 9,
    name: 'Bennett DroneSoc',
    tag1: 'drones',
    tag2: 'technology',
    tag3: 'photography',
    tag4: 'all',
    stacks1: 'Drones',
    stacks2: 'Photography',
    stacks3: 'Aerial technology',
    accent: '#564d52',
    bgimage: require('../assets/images/23.png'),
    image: require('../assets/logos/drone.png'),
    desc: 'Bennett DroneSoc is your gateway to aerial technolology. Discover the art of flying drones, explore aerial photography, and learn about the latest drone innovations.' }, 
  {
    id: 10,
    name: 'Bennett Institute of AI Studies (BIAS)',
    tag1: 'ai',
    tag2: 'ml',
    tag3: 'technology',
    tag4: 'all',
    stacks1: 'AI',
    stacks2: 'Machine Learning',
    stacks3: 'Neural Network',
    accent: '#b01c33',
    bgimage: require('../assets/images/red.png'),
    image: require('../assets/logos/bais.png'),
    desc: ' BIAS (Bennett Institute of AI Studies) is your gateway to the fascinating world of Artificial Intelligence (AI). Join us to understand AIs impact on various domains and dive deep into machine learning and neural networks.' },
  {
    id: 11,
    name: 'Quantum Computing',
    tag1: 'quantum',
    tag2: 'technology',
    tag3: 'science',
    tag4: 'all',
    stacks1: 'Science',
    stacks2: 'Supercomputers',
    stacks3: 'Research',
    accent: '#333333',
    bgimage: require('../assets/images/4.png'),
    image: require('../assets/logos/Quantum.png'),
    desc: 'Quantum Computing Club is where you will explore the exciting and emerging field of quantum computing. Understand the principles and potential applications of quantum computers.' },
  {
    id: 12,
    name: 'Devops Club',
    tag1: 'devops',
    tag2: 'automation',
    tag3: 'technology',
    tag4: 'all',
    stacks1: 'Devops',
    stacks2: 'Learn Automation',
    stacks3: 'Deployment',
    accent: '#5271ff',
    bgimage: require('../assets/images/19.png'),
    image: require('../assets/logos/DEVOPS.png'),
    desc: 'Devops Club is your introduction to the world of DevOps (Development and Operations). Learn how to automate software development and deployment processes.' },
  {
    id: 13,
    name: 'Full Stack Club',
    tag1: 'web',
    tag2: 'fullstack',
    tag3: 'technology',
    tag4: 'all',
    stacks1: 'Front-End',
    stacks2: 'Back-End',
    stacks3: 'Web App',
    accent: '#5271ff',
    bgimage: require('../assets/images/19.png'),
    image: require('../assets/logos/FULLSTACK.png'),
    desc: 'Full Stack Club is your path to becoming a well-rounded web developer. Learn both front-end and back-end technologies to create complete web applications.' },
  {
    id: 14,
    name: 'IEEE WIE',
    tag1: 'engineering',
    tag2: 'inclusivity',
    tag3: 'technology',
    tag4: 'all',
    stacks1: 'Diversity',
    stacks2: 'Inclusivity',
    stacks3: 'Community',
    accent: '#75308b',
    bgimage: require('../assets/images/10.png'),
    image: require('../assets/logos/wie.png'),
    desc: 'IEEE Women in Engineering (WIE) empowers women in technology. Be part of a supportive community focused on gender diversity and inclusivity in technology.' },
  {
    id: 15,
    name: 'Geeks for Geeks BU',
    tag1: 'coding',
    tag2: 'programming',
    tag3: 'technology',
    tag4: 'all',
    stacks1: 'Problem Solving',
    stacks2: 'Projects',
    stacks3: 'Challenges',
    accent: '#348c3f',
    bgimage: require('../assets/images/11.png'),
    image: require('../assets/logos/gfg.png'),
    cname: 'Neze Papreja',
    vname: 'Anushka Sharma',
    chair: require('../assets/team/gfg.jpg'),
    vc: require('../assets/team/gfgv.jpg'),
    desc: 'GeeksforGeeks: Student tech club. Boost skills, teamwork on projects, code battles, and knowledge-sharing in computer science and programming. Join the passionate learning community!' ,
    vis: 'GeeksforGeeks: Learn, Practice, Excel. We empower programmers worldwide with top-notch courses, fostering a global learning community. Unleash your potential, stay ahead in tech, make your mark.',
    pic: 'yes',
    img1: require('../assets/events/gfg3.jpg'),
    img2: require('../assets/events/gfg1.jpg'),
    img3: require('../assets/events/gfg2.jpg')}, 
  {
    id: 16,
    name: 'Technotix',
    tag1: 'gadgets',
    tag2: 'discussion',
    tag3: 'technology',
    tag4: 'all',
    stacks1: 'Discussion',
    stacks2: 'technology Trends',
    stacks3: 'Research',
    accent: '#19eeb2',
    bgimage: require('../assets/images/12.png'),
    image: require('../assets/logos/technotics.png'),
    desc: 'technotix is the club for technology enthusiasts. Stay updated on the latest technology trends, gadgets, and breakthroughs. Engage in technology discussions and hands-on projects.' },
  {
    id: 17,
    name: 'Indian Blockchain Fraternity',
    tag1: 'blockchain',
    tag2: 'cryptocurrency',
    tag3: 'technology',
    tag4: 'all',
    stacks1: 'Smart Contracts',
    stacks2: 'Cryptocurrency',
    stacks3: 'Research',
    accent: '#012251',
    bgimage: require('../assets/images/13.png'),
    image: require('../assets/logos/ibf.png'),
    desc: 'Join the Indian Blockchain Fraternity and explore the disruptive potential of blockchain technology. Dive into the world of cryptocurrencies, smart contracts, and decentralized applications.' },
  {
    id: 18,
    name: 'Solace Studio (Gaming)',
    tag1: 'gaming',
    tag2: 'esports',
    tag3: 'entertainment',
    tag4: 'all',
    stacks1: 'Gaming',
    stacks2: 'Esports',
    stacks3: 'Game Design',
    accent: '#b873dd',
    bgimage: require('../assets/images/14.png'),
    image: require('../assets/logos/solace.png'),
    desc: 'Solace Studio is the place for gaming enthusiasts. From game design and development to esports, join us to explore the world of gaming and interactive media.' },
  {
    id: 19,
    name: 'Ciphers (Cyber Sec)',
    tag1: 'cybersecurity',
    tag2: 'security',
    tag3: 'technology',
    tag4: 'all',
    stacks1: 'Ethical Hacking',
    stacks2: 'Security',
    stacks3: 'Cyber',
    accent: '#7ca894',
    bgimage: require('../assets/images/15.png'),
    image: require('../assets/logos/cipher.png'),
    desc: 'Ciphers is your ticket to the world of cybersecurity and ethical hacking. Learn how to protect digital assets and information while discovering vulnerabilities in a controlled environment.' },
  {
    id: 20,
    name: 'Robotic Process Automation (RPA)',
    tag1: 'automation',
    tag2: 'robots',
    tag3: 'technology',
    tag4: 'all',
    stacks1: 'Automate',
    stacks2: 'Innovate',
    stacks3: 'Collaborate',
    accent: '#5271ff',
    bgimage: require('../assets/images/19.png'),
    image: require('../assets/logos/RPA.png'),
    cname: 'Anshuman Pandey',
    vname: 'Krishna Singh',
    chair: require('../assets/team/rpa.jpg'),
    vc: require('../assets/team/rpav.jpg'),
    desc: 'RPA is a tech marvel automating tasks, like virtual assistants. Our goal: simplify, give hands-on experience, and boost innovation. We will decode bots, streamline processes, and enhance efficiency together.' ,
    vis: 'Imagine our club as an innovation hub for RPA enthusiasts. We are not just about efficiency; we are creating a world where tasks are automated, freeing creativity. Join us in shaping a future of human-robot collaboration.',
    pic: 'no',
    img1: require('../assets/events/soon.png'),
    img2: require('../assets/events/soon.png'),
    img3: require('../assets/events/soon.png')},
    
    {
    id: 21,
    name: 'Data Science',
    tag1: 'visualization',
    tag2: 'data',
    tag3: 'technology',
    tag4: 'all',
    stacks1: 'Visualization',
    stacks2: 'Processing',
    stacks3: 'Analysis',
    accent: '#5271ff',
    bgimage: require('../assets/images/19.png'),
    image: require('../assets/logos/data.png'),
    desc: 'Data Science Club at Bennett University is where data enthusiasts come together. We explore data analysis, visualization, and machine learning to derive meaningful insights from data.' },
  {
    id: 22,
    name: 'ALTReality (AR/VR)',
    tag1: 'ar',
    tag2: 'vr',
    tag3: 'gaming',
    tag4: 'all',
    stacks1: 'Immersive',
    stacks2: 'Gaming',
    stacks3: 'technologynology',
    accent: '#281b25',
    bgimage: require('../assets/images/23.png'),
    image: require('../assets/logos/alt.png'),
    desc: 'ALTReality is all about diving into the immersive worlds of Augmented Reality (AR) and Virtual Reality (VR). Explore the potential of AR and VR technologies, from gaming to real-world applications.' },
  
]